[package]
name = "app"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
epi = { version = "0.14.0"}
eframe = { version = "0.14.0", features = ["time"] }
egui = { version = "0.14.2"}