name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependence
      run: sudo apt-get install libxcb-shape lxcb-xfixes lxkbcommon -y
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
